<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?= $this->tag->getTitle() ?>
    <?//= $this->tag->javascriptInclude('js/jquery.min.js') ?>
    <?= $this->tag->stylesheetLink('css/main.css') ?>
</head>
<body>
<div class="container">
	<div class="head">
		<h1 class="title"><?= $this->config->alliance->title ?></h1>
		<ul class="menu">
			<li class="active"><a href="/killboard/kills">Kills</a></li>
			<li><a href="/killboard/losses">Losses</a></li>
			<li><a href="/killboard/corps">Corporations</a></li>
			<li><a href="/killboard/members">Members</a></li>
		</ul>
	</div>
	<?= $this->getContent() ?>
</div>
</body>
</html>