<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<?= $this->tag->getTitle() ?>
	<?//= $this->tag->javascriptInclude('js/jquery.min.js') ?>
	<?= $this->tag->stylesheetLink('css/main.css') ?>
</head>
<body>
<div class="container">
	<div class="head">
		<h1 class="title"><?= $this->config->alliance->title ?></h1>
		<ul class="menu">
			<? $actionName = $this->getView()->getActionName() ?>

			<li<? if ($actionName === 'kills'): ?> class="active"<? endif ?>>
				<?= $this->tag->linkTo('killboard/kills', 'Kills') ?>
			</li>
			<li<? if ($actionName === 'losses'): ?> class="active"<? endif ?>>
				<?= $this->tag->linkTo('killboard/losses/alliance/' . $this->config->alliance->id, 'Losses') ?>
			</li>
			<? /*
			<li<? if ($actionName === 'corps'): ?> class="active"<? endif ?>>
				<?= $this->tag->linkTo('killboard/corps', 'Corporations') ?>
			</li>
			<li<? if ($actionName === 'members'): ?> class="active"<? endif ?>>
				<?= $this->tag->linkTo('killboard/members', 'Members') ?>
			</li>
			*/ ?>
		</ul>
	</div>
	<?= $this->getContent() ?>
</div>
</body>
</html>