<? if (empty($kills)): ?>
<h2 class="subtitle">No kills committed yet...</h2>
<? else: ?>
<table class="killtable">
	<colgroup>
		<col width="15%">
		<col width="20%">
		<col width="20%">
		<col width="20%">
		<col width="20%">
		<col width="5%">
	</colgroup>
	<thead>
		<tr>
			<th>Date / Time</th>
			<th>Victim</th>
			<th>Property</th>
			<th>Corporation</th>
			<th>Alliance</th>
			<th>Involved</th>
		</tr>
	</thead>
	<tbody>
		<? foreach ($kills as $kill): ?>
		<tr>
			<td><?= $kill->committed ?></td>
			<td>
				<? if ($kill->character_id != 0): ?>
				<a href="#<?= $kill->character_id ?>"><?= $kill->character_name ?></a>
				<? else: ?>
				<span class="victim-corp">Corporation property</span>
				<? endif ?>
			</td>
			<td>
				<a href="#<?= $kill->item_id ?>"><?= $kill->item_title ?></a>
			</td>
			<td>
				<? if ($kill->corp_id != 0): ?>
				<a href="#<?= $kill->corp_id ?>"><?= $kill->corp_title ?></a>
				<? endif ?>
			</td>
			<td>
				<? if ($kill->alliance_id != 0): ?>
				<a href="#<?= $kill->alliance_id ?>"><?= $kill->alliance_title ?></a>
				<? endif ?>
			</td>
			<td><?= $kill->involved_number ?></td>
		</tr>
		<? endforeach ?>
	</tbody>
</table>
<? endif ?>